// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MainSurfaceProto.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Enums
  public enum BuyResult {
    Sucess = 0,
    Gold = 1,
    Limit = 2,
  }

  public enum RedPointType {
    BagAddGoods = 0,
    ShopAddNew = 1,
    ShopUpdate = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端发送给服务器获取角色主城信息
  /// </summary>
  public sealed class C_To_S_GetPlayerInfo_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_GetPlayerInfo_Msg> _parser = new pb::MessageParser<C_To_S_GetPlayerInfo_Msg>(() => new C_To_S_GetPlayerInfo_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_GetPlayerInfo_Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  ///服务器发送给客户端商品信息
  /// </summary>
  public sealed class S_To_C_GetPlayerInfo_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_GetPlayerInfo_Msg> _parser = new pb::MessageParser<S_To_C_GetPlayerInfo_Msg>(() => new S_To_C_GetPlayerInfo_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_GetPlayerInfo_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "player_info" field.</summary>
    public const int PlayerInfoFieldNumber = 1;
    private global::MyGame.PlayerInfo playerInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.PlayerInfo PlayerInfo {
      get { return playerInfo_; }
      set {
        playerInfo_ = value;
      }
    }

    /// <summary>Field number for the "bag_info_dict" field.</summary>
    public const int BagInfoDictFieldNumber = 2;
    private static readonly pbc::MapField<int, global::MyGame.BagInfo>.Codec _map_bagInfoDict_codec
        = new pbc::MapField<int, global::MyGame.BagInfo>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::MyGame.BagInfo.Parser), 18);
    private readonly pbc::MapField<int, global::MyGame.BagInfo> bagInfoDict_ = new pbc::MapField<int, global::MyGame.BagInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::MyGame.BagInfo> BagInfoDict {
      get { return bagInfoDict_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (playerInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PlayerInfo);
      }
      bagInfoDict_.WriteTo(output, _map_bagInfoDict_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (playerInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerInfo);
      }
      size += bagInfoDict_.CalculateSize(_map_bagInfoDict_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (playerInfo_ == null) {
              playerInfo_ = new global::MyGame.PlayerInfo();
            }
            input.ReadMessage(playerInfo_);
            break;
          }
          case 18: {
            bagInfoDict_.AddEntriesFrom(input, _map_bagInfoDict_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class PlayerInfo : pb::IMessage {
    private static readonly pb::MessageParser<PlayerInfo> _parser = new pb::MessageParser<PlayerInfo>(() => new PlayerInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerInfo> Parser { get { return _parser; } }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 1;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 2;
    private int gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Level != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Level);
      }
      if (Gold != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Gold);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Gold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Level = input.ReadInt32();
            break;
          }
          case 16: {
            Gold = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端发送给服务器获取商品信息
  /// </summary>
  public sealed class C_To_S_GetShopInfos_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_GetShopInfos_Msg> _parser = new pb::MessageParser<C_To_S_GetShopInfos_Msg>(() => new C_To_S_GetShopInfos_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_GetShopInfos_Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  ///服务器发送给客户端商品信息
  /// </summary>
  public sealed class S_To_C_GetShopInfos_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_GetShopInfos_Msg> _parser = new pb::MessageParser<S_To_C_GetShopInfos_Msg>(() => new S_To_C_GetShopInfos_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_GetShopInfos_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "shop_info_list" field.</summary>
    public const int ShopInfoListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.ShopInfo> _repeated_shopInfoList_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.ShopInfo.Parser);
    private readonly pbc::RepeatedField<global::MyGame.ShopInfo> shopInfoList_ = new pbc::RepeatedField<global::MyGame.ShopInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.ShopInfo> ShopInfoList {
      get { return shopInfoList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      shopInfoList_.WriteTo(output, _repeated_shopInfoList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += shopInfoList_.CalculateSize(_repeated_shopInfoList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            shopInfoList_.AddEntriesFrom(input, _repeated_shopInfoList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端发送给服务器获取商品信息
  /// </summary>
  public sealed class C_To_S_BuyShop_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_BuyShop_Msg> _parser = new pb::MessageParser<C_To_S_BuyShop_Msg>(() => new C_To_S_BuyShop_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_BuyShop_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 2;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 3;
    private int price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Count != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Count);
      }
      if (Price != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Price);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Count = input.ReadInt32();
            break;
          }
          case 24: {
            Price = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器发送给客户端购买商品结果
  /// </summary>
  public sealed class S_To_C_BuyShop_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_BuyShop_Msg> _parser = new pb::MessageParser<S_To_C_BuyShop_Msg>(() => new S_To_C_BuyShop_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_BuyShop_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "buy_r" field.</summary>
    public const int BuyRFieldNumber = 1;
    private global::MyGame.BuyResult buyR_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.BuyResult BuyR {
      get { return buyR_; }
      set {
        buyR_ = value;
      }
    }

    /// <summary>Field number for the "shop_info" field.</summary>
    public const int ShopInfoFieldNumber = 2;
    private global::MyGame.ShopInfo shopInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.ShopInfo ShopInfo {
      get { return shopInfo_; }
      set {
        shopInfo_ = value;
      }
    }

    /// <summary>Field number for the "bag_info" field.</summary>
    public const int BagInfoFieldNumber = 3;
    private global::MyGame.BagInfo bagInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.BagInfo BagInfo {
      get { return bagInfo_; }
      set {
        bagInfo_ = value;
      }
    }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 4;
    private int gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BuyR != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BuyR);
      }
      if (shopInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShopInfo);
      }
      if (bagInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BagInfo);
      }
      if (Gold != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Gold);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BuyR != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BuyR);
      }
      if (shopInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShopInfo);
      }
      if (bagInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BagInfo);
      }
      if (Gold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            buyR_ = (global::MyGame.BuyResult) input.ReadEnum();
            break;
          }
          case 18: {
            if (shopInfo_ == null) {
              shopInfo_ = new global::MyGame.ShopInfo();
            }
            input.ReadMessage(shopInfo_);
            break;
          }
          case 26: {
            if (bagInfo_ == null) {
              bagInfo_ = new global::MyGame.BagInfo();
            }
            input.ReadMessage(bagInfo_);
            break;
          }
          case 32: {
            Gold = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///商品信息
  /// </summary>
  public sealed class ShopInfo : pb::IMessage {
    private static readonly pb::MessageParser<ShopInfo> _parser = new pb::MessageParser<ShopInfo>(() => new ShopInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopInfo> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 2;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Count != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Count);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class BagInfo : pb::IMessage {
    private static readonly pb::MessageParser<BagInfo> _parser = new pb::MessageParser<BagInfo>(() => new BagInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagInfo> Parser { get { return _parser; } }

    /// <summary>Field number for the "cellId" field.</summary>
    public const int CellIdFieldNumber = 1;
    private int cellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CellId {
      get { return cellId_; }
      set {
        cellId_ = value;
      }
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 3;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CellId);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (Count != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Count);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellId);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            CellId = input.ReadInt32();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_To_C_RedPoint_Update_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_RedPoint_Update_Msg> _parser = new pb::MessageParser<S_To_C_RedPoint_Update_Msg>(() => new S_To_C_RedPoint_Update_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_RedPoint_Update_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "redPointDataList" field.</summary>
    public const int RedPointDataListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.RedPointData> _repeated_redPointDataList_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.RedPointData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.RedPointData> redPointDataList_ = new pbc::RepeatedField<global::MyGame.RedPointData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.RedPointData> RedPointDataList {
      get { return redPointDataList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      redPointDataList_.WriteTo(output, _repeated_redPointDataList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += redPointDataList_.CalculateSize(_repeated_redPointDataList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            redPointDataList_.AddEntriesFrom(input, _repeated_redPointDataList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_RedPoint_Update_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_RedPoint_Update_Msg> _parser = new pb::MessageParser<C_To_S_RedPoint_Update_Msg>(() => new C_To_S_RedPoint_Update_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_RedPoint_Update_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "redPointData" field.</summary>
    public const int RedPointDataFieldNumber = 1;
    private global::MyGame.RedPointData redPointData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.RedPointData RedPointData {
      get { return redPointData_; }
      set {
        redPointData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (redPointData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RedPointData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (redPointData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RedPointData);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (redPointData_ == null) {
              redPointData_ = new global::MyGame.RedPointData();
            }
            input.ReadMessage(redPointData_);
            break;
          }
        }
      }
    }

  }

  public sealed class RedPointData : pb::IMessage {
    private static readonly pb::MessageParser<RedPointData> _parser = new pb::MessageParser<RedPointData>(() => new RedPointData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RedPointData> Parser { get { return _parser; } }

    /// <summary>Field number for the "redPointId" field.</summary>
    public const int RedPointIdFieldNumber = 1;
    private int redPointId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RedPointId {
      get { return redPointId_; }
      set {
        redPointId_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::MyGame.RedPointType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.RedPointType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private bool state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RedPointId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RedPointId);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (State != false) {
        output.WriteRawTag(24);
        output.WriteBool(State);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RedPointId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RedPointId);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (State != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RedPointId = input.ReadInt32();
            break;
          }
          case 16: {
            type_ = (global::MyGame.RedPointType) input.ReadEnum();
            break;
          }
          case 24: {
            State = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
