// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Goods.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Messages
  public sealed class GoodsData : pb::IMessage {
    private static readonly pb::MessageParser<GoodsData> _parser = new pb::MessageParser<GoodsData>(() => new GoodsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GoodsData> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inventoryType" field.</summary>
    public const int InventoryTypeFieldNumber = 4;
    private string inventoryType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InventoryType {
      get { return inventoryType_; }
      set {
        inventoryType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "equipType" field.</summary>
    public const int EquipTypeFieldNumber = 5;
    private string equipType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EquipType {
      get { return equipType_; }
      set {
        equipType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sale" field.</summary>
    public const int SaleFieldNumber = 6;
    private string sale_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sale {
      get { return sale_; }
      set {
        sale_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "starLevel" field.</summary>
    public const int StarLevelFieldNumber = 7;
    private string starLevel_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StarLevel {
      get { return starLevel_; }
      set {
        starLevel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quality" field.</summary>
    public const int QualityFieldNumber = 8;
    private string quality_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality {
      get { return quality_; }
      set {
        quality_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "damage" field.</summary>
    public const int DamageFieldNumber = 9;
    private string damage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Damage {
      get { return damage_; }
      set {
        damage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 10;
    private string hp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Hp {
      get { return hp_; }
      set {
        hp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "power" field.</summary>
    public const int PowerFieldNumber = 11;
    private string power_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Power {
      get { return power_; }
      set {
        power_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Des" field.</summary>
    public const int DesFieldNumber = 12;
    private string des_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Des {
      get { return des_; }
      set {
        des_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 13;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (InventoryType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InventoryType);
      }
      if (EquipType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(EquipType);
      }
      if (Sale.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Sale);
      }
      if (StarLevel.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StarLevel);
      }
      if (Quality.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Quality);
      }
      if (Damage.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Damage);
      }
      if (Hp.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Hp);
      }
      if (Power.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Power);
      }
      if (Des.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Des);
      }
      if (Num != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Num);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (InventoryType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InventoryType);
      }
      if (EquipType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EquipType);
      }
      if (Sale.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sale);
      }
      if (StarLevel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StarLevel);
      }
      if (Quality.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality);
      }
      if (Damage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Damage);
      }
      if (Hp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hp);
      }
      if (Power.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Power);
      }
      if (Des.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Des);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            InventoryType = input.ReadString();
            break;
          }
          case 42: {
            EquipType = input.ReadString();
            break;
          }
          case 50: {
            Sale = input.ReadString();
            break;
          }
          case 58: {
            StarLevel = input.ReadString();
            break;
          }
          case 66: {
            Quality = input.ReadString();
            break;
          }
          case 74: {
            Damage = input.ReadString();
            break;
          }
          case 82: {
            Hp = input.ReadString();
            break;
          }
          case 90: {
            Power = input.ReadString();
            break;
          }
          case 98: {
            Des = input.ReadString();
            break;
          }
          case 104: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_ShopGoods : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_ShopGoods> _parser = new pb::MessageParser<C_To_S_ShopGoods>(() => new C_To_S_ShopGoods());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_ShopGoods> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class S_To_C_ShopGoods : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_ShopGoods> _parser = new pb::MessageParser<S_To_C_ShopGoods>(() => new S_To_C_ShopGoods());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_ShopGoods> Parser { get { return _parser; } }

    /// <summary>Field number for the "goodsdatalist" field.</summary>
    public const int GoodsdatalistFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.GoodsData> _repeated_goodsdatalist_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.GoodsData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.GoodsData> goodsdatalist_ = new pbc::RepeatedField<global::MyGame.GoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.GoodsData> Goodsdatalist {
      get { return goodsdatalist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      goodsdatalist_.WriteTo(output, _repeated_goodsdatalist_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += goodsdatalist_.CalculateSize(_repeated_goodsdatalist_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            goodsdatalist_.AddEntriesFrom(input, _repeated_goodsdatalist_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class BagGoodsData : pb::IMessage {
    private static readonly pb::MessageParser<BagGoodsData> _parser = new pb::MessageParser<BagGoodsData>(() => new BagGoodsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagGoodsData> Parser { get { return _parser; } }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::MyGame.GoodsData data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.GoodsData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (data_ == null) {
              data_ = new global::MyGame.GoodsData();
            }
            input.ReadMessage(data_);
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_BagGoods : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_BagGoods> _parser = new pb::MessageParser<C_To_S_BagGoods>(() => new C_To_S_BagGoods());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_BagGoods> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class S_To_C_BagGoods : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_BagGoods> _parser = new pb::MessageParser<S_To_C_BagGoods>(() => new S_To_C_BagGoods());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_BagGoods> Parser { get { return _parser; } }

    /// <summary>Field number for the "bagitemlist" field.</summary>
    public const int BagitemlistFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.BagGoodsData> _repeated_bagitemlist_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.BagGoodsData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.BagGoodsData> bagitemlist_ = new pbc::RepeatedField<global::MyGame.BagGoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.BagGoodsData> Bagitemlist {
      get { return bagitemlist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      bagitemlist_.WriteTo(output, _repeated_bagitemlist_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += bagitemlist_.CalculateSize(_repeated_bagitemlist_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            bagitemlist_.AddEntriesFrom(input, _repeated_bagitemlist_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_BuyGood : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_BuyGood> _parser = new pb::MessageParser<C_To_S_BuyGood>(() => new C_To_S_BuyGood());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_BuyGood> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_To_C_BuyGood : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_BuyGood> _parser = new pb::MessageParser<S_To_C_BuyGood>(() => new S_To_C_BuyGood());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_BuyGood> Parser { get { return _parser; } }

    /// <summary>Field number for the "isbuy" field.</summary>
    public const int IsbuyFieldNumber = 1;
    private bool isbuy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Isbuy {
      get { return isbuy_; }
      set {
        isbuy_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Isbuy != false) {
        output.WriteRawTag(8);
        output.WriteBool(Isbuy);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Isbuy != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Isbuy = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_SendGood : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_SendGood> _parser = new pb::MessageParser<C_To_S_SendGood>(() => new C_To_S_SendGood());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_SendGood> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_To_C_SendGood : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_SendGood> _parser = new pb::MessageParser<S_To_C_SendGood>(() => new S_To_C_SendGood());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_SendGood> Parser { get { return _parser; } }

    /// <summary>Field number for the "bagitemlist" field.</summary>
    public const int BagitemlistFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.BagGoodsData> _repeated_bagitemlist_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.BagGoodsData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.BagGoodsData> bagitemlist_ = new pbc::RepeatedField<global::MyGame.BagGoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.BagGoodsData> Bagitemlist {
      get { return bagitemlist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      bagitemlist_.WriteTo(output, _repeated_bagitemlist_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += bagitemlist_.CalculateSize(_repeated_bagitemlist_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            bagitemlist_.AddEntriesFrom(input, _repeated_bagitemlist_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
