// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Enums
  public enum ItemType {
    Res = 0,
    AddTime = 1,
    Buff = 2,
    Equip = 3,
    Other = 4,
  }

  public enum AddResType {
    Food = 0,
    Wood = 1,
    Diamond = 2,
  }

  #endregion

  #region Messages
  public sealed class NetBagData : pb::IMessage {
    private static readonly pb::MessageParser<NetBagData> _parser = new pb::MessageParser<NetBagData>(() => new NetBagData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetBagData> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "itemIndex" field.</summary>
    public const int ItemIndexFieldNumber = 3;
    private int itemIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemIndex {
      get { return itemIndex_; }
      set {
        itemIndex_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 4;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (ItemIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemIndex);
      }
      if (Count != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Count);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (ItemIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemIndex);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            ItemIndex = input.ReadInt32();
            break;
          }
          case 32: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class NetPlayerData : pb::IMessage {
    private static readonly pb::MessageParser<NetPlayerData> _parser = new pb::MessageParser<NetPlayerData>(() => new NetPlayerData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetPlayerData> Parser { get { return _parser; } }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private int playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 2;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "passWord" field.</summary>
    public const int PassWordFieldNumber = 3;
    private string passWord_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PassWord {
      get { return passWord_; }
      set {
        passWord_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "food" field.</summary>
    public const int FoodFieldNumber = 4;
    private int food_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Food {
      get { return food_; }
      set {
        food_ = value;
      }
    }

    /// <summary>Field number for the "wood" field.</summary>
    public const int WoodFieldNumber = 5;
    private int wood_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Wood {
      get { return wood_; }
      set {
        wood_ = value;
      }
    }

    /// <summary>Field number for the "diamond" field.</summary>
    public const int DiamondFieldNumber = 6;
    private int diamond_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Diamond {
      get { return diamond_; }
      set {
        diamond_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerId);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (PassWord.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PassWord);
      }
      if (Food != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Food);
      }
      if (Wood != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Wood);
      }
      if (Diamond != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Diamond);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
      }
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (PassWord.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PassWord);
      }
      if (Food != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Food);
      }
      if (Wood != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Wood);
      }
      if (Diamond != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diamond);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadInt32();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 26: {
            PassWord = input.ReadString();
            break;
          }
          case 32: {
            Food = input.ReadInt32();
            break;
          }
          case 40: {
            Wood = input.ReadInt32();
            break;
          }
          case 48: {
            Diamond = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_To_C_GetPlayerData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_GetPlayerData_Msg> _parser = new pb::MessageParser<S_To_C_GetPlayerData_Msg>(() => new S_To_C_GetPlayerData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_GetPlayerData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "playerData" field.</summary>
    public const int PlayerDataFieldNumber = 1;
    private global::MyGame.NetPlayerData playerData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.NetPlayerData PlayerData {
      get { return playerData_; }
      set {
        playerData_ = value;
      }
    }

    /// <summary>Field number for the "bagDataDict" field.</summary>
    public const int BagDataDictFieldNumber = 2;
    private static readonly pbc::MapField<int, global::MyGame.NetBagData>.Codec _map_bagDataDict_codec
        = new pbc::MapField<int, global::MyGame.NetBagData>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::MyGame.NetBagData.Parser), 18);
    private readonly pbc::MapField<int, global::MyGame.NetBagData> bagDataDict_ = new pbc::MapField<int, global::MyGame.NetBagData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::MyGame.NetBagData> BagDataDict {
      get { return bagDataDict_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (playerData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PlayerData);
      }
      bagDataDict_.WriteTo(output, _map_bagDataDict_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (playerData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerData);
      }
      size += bagDataDict_.CalculateSize(_map_bagDataDict_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (playerData_ == null) {
              playerData_ = new global::MyGame.NetPlayerData();
            }
            input.ReadMessage(playerData_);
            break;
          }
          case 18: {
            bagDataDict_.AddEntriesFrom(input, _map_bagDataDict_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_GetPlayerData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_GetPlayerData_Msg> _parser = new pb::MessageParser<C_To_S_GetPlayerData_Msg>(() => new C_To_S_GetPlayerData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_GetPlayerData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private int playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class C_To_S_UseBagItem_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_UseBagItem_Msg> _parser = new pb::MessageParser<C_To_S_UseBagItem_Msg>(() => new C_To_S_UseBagItem_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_UseBagItem_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "bagData" field.</summary>
    public const int BagDataFieldNumber = 1;
    private global::MyGame.NetBagData bagData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.NetBagData BagData {
      get { return bagData_; }
      set {
        bagData_ = value;
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 2;
    private global::MyGame.ItemType itemType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.ItemType ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "addType" field.</summary>
    public const int AddTypeFieldNumber = 3;
    private global::MyGame.AddResType addType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.AddResType AddType {
      get { return addType_; }
      set {
        addType_ = value;
      }
    }

    /// <summary>Field number for the "UpdateCount" field.</summary>
    public const int UpdateCountFieldNumber = 4;
    private int updateCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UpdateCount {
      get { return updateCount_; }
      set {
        updateCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (bagData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BagData);
      }
      if (ItemType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ItemType);
      }
      if (AddType != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AddType);
      }
      if (UpdateCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(UpdateCount);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (bagData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BagData);
      }
      if (ItemType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
      }
      if (AddType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AddType);
      }
      if (UpdateCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpdateCount);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (bagData_ == null) {
              bagData_ = new global::MyGame.NetBagData();
            }
            input.ReadMessage(bagData_);
            break;
          }
          case 16: {
            itemType_ = (global::MyGame.ItemType) input.ReadEnum();
            break;
          }
          case 24: {
            addType_ = (global::MyGame.AddResType) input.ReadEnum();
            break;
          }
          case 32: {
            UpdateCount = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_To_C_UseBagItem_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_UseBagItem_Msg> _parser = new pb::MessageParser<S_To_C_UseBagItem_Msg>(() => new S_To_C_UseBagItem_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_UseBagItem_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "bagData" field.</summary>
    public const int BagDataFieldNumber = 1;
    private global::MyGame.NetBagData bagData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.NetBagData BagData {
      get { return bagData_; }
      set {
        bagData_ = value;
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 2;
    private global::MyGame.ItemType itemType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.ItemType ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "addType" field.</summary>
    public const int AddTypeFieldNumber = 3;
    private global::MyGame.AddResType addType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.AddResType AddType {
      get { return addType_; }
      set {
        addType_ = value;
      }
    }

    /// <summary>Field number for the "UpdateCount" field.</summary>
    public const int UpdateCountFieldNumber = 4;
    private int updateCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UpdateCount {
      get { return updateCount_; }
      set {
        updateCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (bagData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BagData);
      }
      if (ItemType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ItemType);
      }
      if (AddType != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AddType);
      }
      if (UpdateCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(UpdateCount);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (bagData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BagData);
      }
      if (ItemType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
      }
      if (AddType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AddType);
      }
      if (UpdateCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpdateCount);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (bagData_ == null) {
              bagData_ = new global::MyGame.NetBagData();
            }
            input.ReadMessage(bagData_);
            break;
          }
          case 16: {
            itemType_ = (global::MyGame.ItemType) input.ReadEnum();
            break;
          }
          case 24: {
            addType_ = (global::MyGame.AddResType) input.ReadEnum();
            break;
          }
          case 32: {
            UpdateCount = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
