syntax = "proto3";
package myGame;

//玩家状态
enum PlayerType
{
  None=0;
  Dead=1;
}

//玩家位置数据
message C_To_S_PlayerOperation
{
  uint32 playerId = 1;
  float x =2;
  float y =3;
  float z =4;
  float roundY =5;
}

//玩家位置数据
message S_To_C_PlayerOperation
{
  uint32 playerId = 1;
  float x =2;
  float y =3;
  float z =4;
  float roundY =5;
  string PathName = 6;
  string Name = 7;
}

//玩家断开链接
message C_To_S_Disconnect
{
	uint32 playerId = 1;
}
//玩家断开链接
message S_To_C_Disconnect
{
	uint32 playerId = 1;
}
//旋转数据xyz三轴
message RotationData
{
	float x =1;
	float y =2;
	float z =3;
}
//发射子弹
message C_To_S_Bullet
{
	uint32 playerId = 1;
	float x =2;
	float y =3;
	float z =4;
	int32 atk = 5;
	uint32 BulletID = 6;
	RotationData rotation = 7;
}
//发射子弹
message S_To_C_Bullet
{
	uint32 playerId = 1;
	float x =2;
	float y =3;
	float z =4;
	int32 atk = 5;
	uint32 BulletID = 6;
	RotationData rotation = 7;
}
//删除子弹
message C_To_S_RemoveBullet
{
	uint32 BulletID = 6;
}
//删除子弹
message S_To_C_RemoveBullet
{
	uint32 BulletID = 6;
}
//攻击消息
message C_To_S_PlayerAtk
{
  uint32 AtkPlayerId=1;
  uint32 BAtkPlayerId=2;
  uint32 BulletID = 6;
}
//玩家血量
message S_To_C_PlayerHp
{
  uint32 PlayerId=1;
  uint32 Hp=2;
  PlayerType type=3;
}
//玩家死亡
message C_To_S_PlayerAlive
{
  uint32 PlayerId=1;
  PlayerType type=3;
}
//玩家动画类型枚举
enum PlayerAniType
{
	BoolType = 0;
	IsTriggerType = 1;
	IntType = 2;
}
//玩家动画
message C_To_S_PlayerAnimator
{
	uint32 PlayerId=1;
	string AnimatorName=2;
	bool aniType = 3;
	PlayerAniType type = 4;
}//玩家动画
message S_To_C_PlayerAnimator
{
	  uint32 PlayerId=1;
	  string AnimatorName=2;
	  bool aniType = 3;
	  PlayerAniType type = 4;
}
//玩家退出游戏，并非断开连接
message C_To_S_ExitGame
{
	uint32 playerId = 1;
}
//玩家退出游戏，并非断开连接
message S_To_C_ExitGame
{
	uint32 playerId = 1;
}
//玩家金币增加或扣除消息
message C_To_S_Gold
{
	int32 gold = 1;
}
message S_To_C_Gold
{
	int32 gold = 1;
}
