// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guide.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Messages
  public sealed class C_To_S_Guide_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_Guide_Msg> _parser = new pb::MessageParser<C_To_S_Guide_Msg>(() => new C_To_S_Guide_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_Guide_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "GuideID" field.</summary>
    public const int GuideIDFieldNumber = 1;
    private int guideID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GuideID {
      get { return guideID_; }
      set {
        guideID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GuideID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GuideID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GuideID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GuideID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GuideID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// </summary>
  public sealed class S_To_C_Guide_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Guide_Msg> _parser = new pb::MessageParser<S_To_C_Guide_Msg>(() => new S_To_C_Guide_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Guide_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "GuideID" field.</summary>
    public const int GuideIDFieldNumber = 1;
    private int guideID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GuideID {
      get { return guideID_; }
      set {
        guideID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GuideID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GuideID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GuideID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GuideID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GuideID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
