// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UIMsg.Proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Enums
  /// <summary>
  ///枚举
  /// </summary>
  public enum BayType {
    Success = 0,
    Glod = 1,
    Item = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端请求商城数据
  /// </summary>
  public sealed class C_To_S_GetShopData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_GetShopData_Msg> _parser = new pb::MessageParser<C_To_S_GetShopData_Msg>(() => new C_To_S_GetShopData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_GetShopData_Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  ///服务器返回商城数据
  /// </summary>
  public sealed class S_To_C_GetShopData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_GetShopData_Msg> _parser = new pb::MessageParser<S_To_C_GetShopData_Msg>(() => new S_To_C_GetShopData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_GetShopData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "shopdatas" field.</summary>
    public const int ShopdatasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.ShopData> _repeated_shopdatas_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.ShopData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.ShopData> shopdatas_ = new pbc::RepeatedField<global::MyGame.ShopData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.ShopData> Shopdatas {
      get { return shopdatas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      shopdatas_.WriteTo(output, _repeated_shopdatas_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += shopdatas_.CalculateSize(_repeated_shopdatas_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            shopdatas_.AddEntriesFrom(input, _repeated_shopdatas_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///商店数据
  /// </summary>
  public sealed class ShopData : pb::IMessage {
    private static readonly pb::MessageParser<ShopData> _parser = new pb::MessageParser<ShopData>(() => new ShopData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopData> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inventoryType" field.</summary>
    public const int InventoryTypeFieldNumber = 4;
    private string inventoryType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InventoryType {
      get { return inventoryType_; }
      set {
        inventoryType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "equipTe" field.</summary>
    public const int EquipTeFieldNumber = 5;
    private string equipTe_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EquipTe {
      get { return equipTe_; }
      set {
        equipTe_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sale" field.</summary>
    public const int SaleFieldNumber = 6;
    private int sale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sale {
      get { return sale_; }
      set {
        sale_ = value;
      }
    }

    /// <summary>Field number for the "starLevel" field.</summary>
    public const int StarLevelFieldNumber = 7;
    private int starLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StarLevel {
      get { return starLevel_; }
      set {
        starLevel_ = value;
      }
    }

    /// <summary>Field number for the "quality" field.</summary>
    public const int QualityFieldNumber = 8;
    private int quality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "damage" field.</summary>
    public const int DamageFieldNumber = 9;
    private int damage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Damage {
      get { return damage_; }
      set {
        damage_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 10;
    private int hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "power" field.</summary>
    public const int PowerFieldNumber = 11;
    private int power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    /// <summary>Field number for the "Des" field.</summary>
    public const int DesFieldNumber = 12;
    private string des_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Des {
      get { return des_; }
      set {
        des_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (InventoryType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InventoryType);
      }
      if (EquipTe.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(EquipTe);
      }
      if (Sale != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Sale);
      }
      if (StarLevel != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(StarLevel);
      }
      if (Quality != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Quality);
      }
      if (Damage != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Damage);
      }
      if (Hp != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Hp);
      }
      if (Power != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Power);
      }
      if (Des.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Des);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (InventoryType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InventoryType);
      }
      if (EquipTe.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EquipTe);
      }
      if (Sale != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sale);
      }
      if (StarLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StarLevel);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
      }
      if (Damage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Damage);
      }
      if (Hp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (Power != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Power);
      }
      if (Des.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Des);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            InventoryType = input.ReadString();
            break;
          }
          case 42: {
            EquipTe = input.ReadString();
            break;
          }
          case 48: {
            Sale = input.ReadInt32();
            break;
          }
          case 56: {
            StarLevel = input.ReadInt32();
            break;
          }
          case 64: {
            Quality = input.ReadInt32();
            break;
          }
          case 72: {
            Damage = input.ReadInt32();
            break;
          }
          case 80: {
            Hp = input.ReadInt32();
            break;
          }
          case 88: {
            Power = input.ReadInt32();
            break;
          }
          case 98: {
            Des = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端请求背包数据
  /// </summary>
  public sealed class C_To_S_GetBagData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_GetBagData_Msg> _parser = new pb::MessageParser<C_To_S_GetBagData_Msg>(() => new C_To_S_GetBagData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_GetBagData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "PlayerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private uint playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器返回背包数据
  /// </summary>
  public sealed class S_To_C_GetBagData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_GetBagData_Msg> _parser = new pb::MessageParser<S_To_C_GetBagData_Msg>(() => new S_To_C_GetBagData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_GetBagData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "bagDatas" field.</summary>
    public const int BagDatasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.BagData> _repeated_bagDatas_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.BagData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.BagData> bagDatas_ = new pbc::RepeatedField<global::MyGame.BagData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.BagData> BagDatas {
      get { return bagDatas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      bagDatas_.WriteTo(output, _repeated_bagDatas_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += bagDatas_.CalculateSize(_repeated_bagDatas_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            bagDatas_.AddEntriesFrom(input, _repeated_bagDatas_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class BagData : pb::IMessage {
    private static readonly pb::MessageParser<BagData> _parser = new pb::MessageParser<BagData>(() => new BagData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagData> Parser { get { return _parser; } }

    /// <summary>Field number for the "BagItemID" field.</summary>
    public const int BagItemIDFieldNumber = 1;
    private int bagItemID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BagItemID {
      get { return bagItemID_; }
      set {
        bagItemID_ = value;
      }
    }

    /// <summary>Field number for the "shopData" field.</summary>
    public const int ShopDataFieldNumber = 2;
    private global::MyGame.ShopData shopData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.ShopData ShopData {
      get { return shopData_; }
      set {
        shopData_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 3;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BagItemID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BagItemID);
      }
      if (shopData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShopData);
      }
      if (Count != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Count);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BagItemID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BagItemID);
      }
      if (shopData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShopData);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            BagItemID = input.ReadInt32();
            break;
          }
          case 18: {
            if (shopData_ == null) {
              shopData_ = new global::MyGame.ShopData();
            }
            input.ReadMessage(shopData_);
            break;
          }
          case 24: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器发起购买请求
  /// </summary>
  public sealed class C_To_S_BayShop_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_BayShop_Msg> _parser = new pb::MessageParser<C_To_S_BayShop_Msg>(() => new C_To_S_BayShop_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_BayShop_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "PlayerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private uint playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "GoodID" field.</summary>
    public const int GoodIDFieldNumber = 2;
    private int goodID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodID {
      get { return goodID_; }
      set {
        goodID_ = value;
      }
    }

    /// <summary>Field number for the "BayNum" field.</summary>
    public const int BayNumFieldNumber = 3;
    private int bayNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BayNum {
      get { return bayNum_; }
      set {
        bayNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerId);
      }
      if (GoodID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodID);
      }
      if (BayNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BayNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerId);
      }
      if (GoodID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodID);
      }
      if (BayNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BayNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadUInt32();
            break;
          }
          case 16: {
            GoodID = input.ReadInt32();
            break;
          }
          case 24: {
            BayNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器返回购买后的数据
  /// </summary>
  public sealed class S_To_C_S_BayShop_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_S_BayShop_Msg> _parser = new pb::MessageParser<S_To_C_S_BayShop_Msg>(() => new S_To_C_S_BayShop_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_S_BayShop_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "Glod" field.</summary>
    public const int GlodFieldNumber = 1;
    private int glod_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Glod {
      get { return glod_; }
      set {
        glod_ = value;
      }
    }

    /// <summary>Field number for the "bagData" field.</summary>
    public const int BagDataFieldNumber = 2;
    private global::MyGame.BagData bagData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.BagData BagData {
      get { return bagData_; }
      set {
        bagData_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::MyGame.BayType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.BayType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Glod != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Glod);
      }
      if (bagData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BagData);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Glod != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Glod);
      }
      if (bagData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BagData);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Glod = input.ReadInt32();
            break;
          }
          case 18: {
            if (bagData_ == null) {
              bagData_ = new global::MyGame.BagData();
            }
            input.ReadMessage(bagData_);
            break;
          }
          case 24: {
            type_ = (global::MyGame.BayType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器请求玩家数据
  /// </summary>
  public sealed class C_To_S_GetPlayerData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_GetPlayerData_Msg> _parser = new pb::MessageParser<C_To_S_GetPlayerData_Msg>(() => new C_To_S_GetPlayerData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_GetPlayerData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "PlayerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private uint playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerId = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器返回玩家数据
  /// </summary>
  public sealed class S_To_C_GetPlayerData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_GetPlayerData_Msg> _parser = new pb::MessageParser<S_To_C_GetPlayerData_Msg>(() => new S_To_C_GetPlayerData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_GetPlayerData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "Glod" field.</summary>
    public const int GlodFieldNumber = 1;
    private int glod_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Glod {
      get { return glod_; }
      set {
        glod_ = value;
      }
    }

    /// <summary>Field number for the "bagDatas" field.</summary>
    public const int BagDatasFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MyGame.BagData> _repeated_bagDatas_codec
        = pb::FieldCodec.ForMessage(18, global::MyGame.BagData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.BagData> bagDatas_ = new pbc::RepeatedField<global::MyGame.BagData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.BagData> BagDatas {
      get { return bagDatas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Glod != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Glod);
      }
      bagDatas_.WriteTo(output, _repeated_bagDatas_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Glod != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Glod);
      }
      size += bagDatas_.CalculateSize(_repeated_bagDatas_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Glod = input.ReadInt32();
            break;
          }
          case 18: {
            bagDatas_.AddEntriesFrom(input, _repeated_bagDatas_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
